import type { NextPage } from 'next';
import { useState, useEffect } from "react";
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {

  // const [days, setDays] = useState();
  // const [hours, setHours] = useState();
  // const [minutes, setMinutes] = useState();
  // const [seconds, setSeconds] = useState();

  // useEffect(() => {
  
  //   return () => {
  //     cleanup
  //   }
  // }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="timer-warpper">
        Hello
      </div>
    
    </div>
  )
}

export default Home
